name: EC2 ATS Environment Setup

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  setup-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload and execute setup script on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          echo "🚚 Uploading setup script to EC2..."
          scp -o StrictHostKeyChecking=no -i private_key.pem scripts/setup_environment.sh ${USER}@${HOST}:/home/${USER}/setup_environment.sh

          echo "🚀 Running setup script on EC2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} "bash /home/${USER}/setup_environment.sh"
